# general settings
name: BasicUniVSRFeatPropWithSpyFlowDCN_Fast_CoarseFlow+4Conv_wiOneStageUp_10BLK32CHN_Vimeo90K_BDx4
model_type: VideoRecurrentModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KRecurrentDataset
    dataroot_gt: /data2/yangxi/datasets/Vimeo90k/vimeo_septuplet/sequences
    dataroot_lq: /data2/yangxi/datasets/Vimeo90k/vimeo_septuplet_GaussianLRx4/sequences
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: -1
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: Vid4
    type: VideoRecurrentTestDataset
    dataroot_gt: /data2/yangxi/datasets/VSR-TEST/Vid4/GT
    dataroot_lq: /data2/yangxi/datasets/VSR-TEST/Vid4/Gaussian4xLR

    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed

#network structures
#network_g:
#  type: BasicUniVSRFeatPropWithPCDAlign
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 10
#  deformable_groups: 8
#  one_stage_up: true

#network_g:
#  type: BasicUniVSRFeatPropWithoutAlign_Fast
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 30
#  one_stage_up: true

# network_g:
#  type: BasicUniVSRFeatPropWithLocalCorr_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  nbr_size: 9

#network_g:
#  type: BasicUniVSRFeatPropWithSpyFlow_FGAC
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 10
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
#  one_stage_up: true

#network_g:
#  type: BasicUniVSRFeatPropWithSpyFlow_Fast
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 10
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
#  one_stage_up: true

#network_g:
# type: BasicUniVSRFeatPropWithFastFlow_Fast
# num_feat: 32
# num_extract_block: 0
# num_block: 10
# flownet_path: experiments/pretrained_models/flownet/fastflownet_ft_sintel.pth
# one_stage_up: true

#network_g:
# type: BasicUniVSRFeatPropWithMaskFlow_Fast
# num_feat: 32
# num_extract_block: 0
# num_block: 10
# flownet_path: experiments/pretrained_models/flownet/maskflownet-ft-sintel.pth
# one_stage_up: true

network_g:
  type: BasicUniVSRFeatPropWithSpyFlowDCN_Fast
  num_feat: 32
  num_extract_block: 0
  num_block: 10
  deformable_groups: 8
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  one_stage_up: true

#network_g:
#  type: BasicUniVSRFeatPropWithFastFlowDCN_Fast
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 10
#  deformable_groups: 8
#  flownet_path: experiments/pretrained_models/flownet/fastflownet_ft_sintel.pth
#  one_stage_up: true

#network_g:
#  type: BasicUniVSRFeatPropWithMaskFlowDCN_Fast
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 10
#  deformable_groups: 8
#  flownet_path: experiments/pretrained_models/flownet/maskflownet-ft-sintel.pth
#  one_stage_up: true

# network_g:
#   type: BasicUniVSRFeatPropWithFlowDeformAtt_Fast_V2
#   num_feat: 64
#   num_extract_block: 0
#   num_block: 20
#   num_levels: 1
#   num_heads: 8
#   num_points: 9
#   max_residue_magnitude: 10
#   spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropWithFlowDeformAtt_ShuffleAtt_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  num_levels: 1
#  num_heads: 8
#  num_points: 9
#  window_size: 8
#  mlp_ratio: 1
#  max_residue_magnitude: 10
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropResBlock
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropRCAB
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropIMDB
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 15
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropEarFusion_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropCrossAttFusion_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  num_heads: 4
#  window_size: 4
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropMidFusion
#  num_feat: 64
#  num_extract_block: 0
#  num_block_1: 10
#  num_block_2: 10
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRDualFeatProp
#  num_feat: 64
#  num_extract_block: 0
#  num_block_1: 10
#  num_block_2: 10
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropTemporalAttFusion
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# num_heads: 2
# deformable_groups: 8
# spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropCoTSTAttFusion
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# num_heads: 2
# deformable_groups: 8
# spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropSepSTSFusion
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# num_heads: 1
# depth: 1
# depth_window_size: [1, 4, 4]
# point_window_size: [2, 1, 1]
# mlp_ratio: 2
# deformable_groups: 8
# spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropWithFlowDCN_Fast_FrmInp3
#  num_feat: 32
#  num_extract_block: 0
#  num_block: 10
#  deformable_groups: 8
#  flownet_path: experiments/pretrained_models/flownet/fastflownet_ft_sintel.pth
#  one_stage_up: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
