# general settings
name: BasicUniVSRFeatPropWithSpyFlowDCN_Fast_V2
model_type: VideoRecurrentModel
scale: 4
num_gpu: auto  # official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: /data2/yangxi/datasets/REDS/train_sharp_sub
    dataroot_lq: /data2/yangxi/datasets/REDS/train_sharp_bicubic_sub
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT_sub.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: false
    io_backend:
      type: disk

    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: /data2/yangxi/datasets/VSR-TEST/REDS4/GT
    dataroot_lq: /data2/yangxi/datasets/VSR-TEST/REDS4/Bicubic4xLR

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed

#network structures
#network_g:
#  type: BasicUniVSRFeatPropWithPCD
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8

#network_g:
#  type: BasicUniVSRFeatPropWithoutAlign_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20

# network_g:
#  type: BasicUniVSRFeatPropWithLocalCorr_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  nbr_size: 9

#network_g:
#  type: BasicUniVSRFeatPropWithSpyFlow_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropWithPWCFlow_Fast
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# flownet_path: ~

#network_g:
# type: BasicUniVSRFeatPropWithFastFlow_Fast
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# flownet_path: experiments/pretrained_models/flownet/fastflownet_ft_mix.pth

#network_g:
#  type: BasicUniVSRFeatPropWithRAFT_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  model: normal
#  flownet_path: experiments/pretrained_models/flownet/raft-sintel.pth

network_g:
  type: BasicUniVSRFeatPropWithSpyFlowDCN_Fast_V2
  num_feat: 64
  num_extract_block: 0
  num_block: 20
  deformable_groups: 8
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropWithFastFlowDCN_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  flownet_path: experiments/pretrained_models/flownet/fastflownet_ft_sintel.pth

# network_g:
#   type: BasicUniVSRFeatPropWithFlowDeformAtt_Fast_V2
#   num_feat: 64
#   num_extract_block: 0
#   num_block: 20
#   num_levels: 1
#   num_heads: 8
#   num_points: 9
#   max_residue_magnitude: 10
#   spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropWithFlowDeformAtt_ShuffleAtt_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  num_levels: 1
#  num_heads: 8
#  num_points: 9
#  window_size: 8
#  mlp_ratio: 1
#  max_residue_magnitude: 10
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropResBlock
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropRCAB
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropIMDB
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 15
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropEarFusion_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropCrossAttFusion_Fast
#  num_feat: 64
#  num_extract_block: 0
#  num_block: 20
#  num_heads: 4
#  window_size: 4
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRFeatPropMidFusion
#  num_feat: 64
#  num_extract_block: 0
#  num_block_1: 10
#  num_block_2: 10
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
#  type: BasicUniVSRDualFeatProp
#  num_feat: 64
#  num_extract_block: 0
#  num_block_1: 10
#  num_block_2: 10
#  deformable_groups: 8
#  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropTemporalAttFusion
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# num_heads: 2
# deformable_groups: 8
# spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropCoTSTAttFusion
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# num_heads: 2
# deformable_groups: 8
# spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_g:
# type: BasicUniVSRFeatPropSepSTSFusion
# num_feat: 64
# num_extract_block: 0
# num_block: 20
# num_heads: 1
# depth: 1
# depth_window_size: [1, 4, 4]
# point_window_size: [2, 1, 1]
# mlp_ratio: 2
# deformable_groups: 8
# spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125
  # dcn_lr_mul: 1.0

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  suffix: ~  # add suffix to saved images, if None, use exp name

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
