# general settings
name: VideoRecurrentGANLDLModel_SpatioTemporalDiscriminator_REDS
model_type: VideoRecurrentSTGANLDLModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: /home/yangxi/datasets/REDS/train_sharp
    dataroot_lq: /home/yangxi/datasets/REDS/train_sharp_bicubic/X4
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 10
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: /home/yangxi/datasets/VSR-TEST/REDS4/test_sharp
    dataroot_lq: /home/yangxi/datasets/VSR-TEST/REDS4/test_sharp_bicubic

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # For recurrent, num_frame has no effect. Set to -1

# network structures
network_g:
  type: BasicVSR
  num_feat: 64
  num_block: 10
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

#network_d:
#  type: VGGStyleDiscriminator
#  num_in_ch: 3
#  num_feat: 32
#  input_size: 256

#network_d:
#  type: UNetDiscriminatorWithSpectralNorm
#  num_in_ch: 3
#  num_feat: 32
#  skip_connection: true

network_d:
  type: SpatioTemporalDiscriminator
  num_in_ch: 3
  num_feat: 32
  num_frame: 3

# path
path:
#  pretrain_network_g: experiments/pretrained_models/BasicVSR/BasicVSR_REDS4-543c8261.pth
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  lr_flow: !!float 0
  optim_d:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [150000]
    gamma: 0.5

  total_iter: 150000
  warmup_iter: -1  # no warm up
  fix_flow: ~

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-2
  ldl_opt:
    type: L1Loss
    loss_weight: !!float 5e2
    reduction: mean

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
