# general settings
name: FlowDCNAlignVSR_x4_SR_REDS_300k_valREDS4
model_type: FlowGuidedDCNVSRModel
scale: 4
num_gpu: auto  # official: 8 GPUs
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSDataset
    #dataroot_gt: /data2/yangxi/datasets/REDS/train_sharp_sub
    #ataroot_lq: /data2/yangxi/datasets/REDS/train_sharp_bicubic_sub
    dataroot_gt: /home/xiyang/Datasets/REDS/train_sharp_sub
    dataroot_lq: /home/xiyang/Datasets/REDS/train_sharp_bicubic_sub
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT_sub.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoTestDataset
    #dataroot_gt: /data2/yangxi/datasets/REDS/train_sharp
    #dataroot_lq: /data2/yangxi/datasets/REDS/train_sharp_bicubic
    dataroot_gt: /home/xiyang/Datasets/REDS/train_sharp
    dataroot_lq: /home/xiyang/Datasets/REDS/train_sharp_bicubic
    meta_info_file: basicsr/data/meta_info/meta_info_REDS4_test_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 5
    padding: reflection_circle

# network structures
network_g:
  type: FlowDCNAlignVSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  center_frame_idx: ~
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000]
    restart_weights: [1, 1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false
  suffix: ~  # add suffix to saved images, if None, use exp name

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true